# Generated by Django 4.2 on 2023-12-18 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keywords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Keyword", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=30)),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("articleUrl", models.URLField()),
                ("articleImgUrl", models.URLField()),
                ("keyword", models.ManyToManyField(blank=True, to="news.keywords")),
            ],
        ),
    ]
