# Generated by Django 4.2 on 2023-12-29 16:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_article_create_dt"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporalyArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("detail", models.TextField()),
                ("category", models.CharField(max_length=50)),
                ("link", models.URLField()),
                ("img", models.URLField()),
                ("create_dt", models.DateTimeField(default=django.utils.timezone.now)),
                ("write_dt", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="sentiment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="write_dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="mynews",
            name="newsid",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="mynews",
            name="save_dt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
