# Generated by Django 4.2 on 2024-01-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_temporalyarticle_article_sentiment_article_write_dt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="keywords",
            field=models.JSONField(default=list),
        ),
    ]
