# Generated by Django 5.0 on 2023-12-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_board_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="notice/"),
        ),
        migrations.AlterField(
            model_name="board",
            name="title",
            field=models.CharField(max_length=60),
        ),
    ]
