# Generated by Django 5.0.2 on 2024-02-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_image_alter_board_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
