# Generated by Django 5.0 on 2023-12-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_is_email_verified_alter_user_emailnotice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="keyword",
            name="code",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
