# Generated by Django 4.2 on 2023-12-28 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_keyword_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyword",
            name="ratio",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="NegativeKeywordInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_dt",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 12, 28, 9, 47, 38, 921720)
                    ),
                ),
                ("negative", models.SmallIntegerField(default=0)),
                (
                    "keyword",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.keyword",
                    ),
                ),
            ],
        ),
    ]
