# Generated by Django 5.0 on 2023-12-28 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_keyword_ratio_negativekeywordinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="negativekeywordinfo",
            name="present",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="negativekeywordinfo",
            name="create_dt",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 28, 16, 22, 57, 428192)
            ),
        ),
    ]
