# Generated by Django 5.0 on 2024-01-04 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_negativekeywordinfo_present_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="smsNotice",
        ),
        migrations.AlterField(
            model_name="negativekeywordinfo",
            name="create_dt",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 4, 14, 23, 6, 338152)
            ),
        ),
    ]
