# Generated by Django 4.2 on 2024-01-09 09:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_user_phone_number_remove_user_smsnotice_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyword",
            name="code",
        ),
        migrations.DeleteModel(
            name="NegativeKeywordInfo",
        ),
    ]
