# Generated by Django 4.2 on 2024-01-09 09:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enterprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("code", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="EnterpriseGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("negative", models.SmallIntegerField(default=0)),
                ("present", models.BigIntegerField(default=0)),
                ("create_dt", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "enterprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="enterprise.enterprise",
                    ),
                ),
            ],
        ),
    ]
